-- Users table (synced from auth.users via trigger)
CREATE TABLE IF NOT EXISTS public.users (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  name TEXT NOT NULL DEFAULT '',
  last_name TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL DEFAULT 'student' CHECK (role IN ('student', 'admin')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Auto-create user row on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (id, email, name, last_name)
  VALUES (
    NEW.id,
    NEW.email,
    NEW.raw_user_meta_data->>'name',
    NEW.raw_user_meta_data->>'lastName'
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Row Level Security
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Users can read their own row
DROP POLICY IF EXISTS "users_read_own" ON public.users;
CREATE POLICY "users_read_own" ON public.users
  FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "users_read_admin" ON public.users;
CREATE POLICY "users_read_admin" ON public.users
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
  );

-- Courses table
CREATE TABLE IF NOT EXISTS public.courses (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name      TEXT NOT NULL,
  slug      TEXT NOT NULL UNIQUE,
  description TEXT,
  image_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;

-- Anyone can read courses (public catalog)
DROP POLICY IF EXISTS "courses_read_public" ON public.courses;
CREATE POLICY "courses_read_public" ON public.courses
  FOR SELECT USING (true);

-- Seed data
INSERT INTO public.courses (name, slug, description) VALUES
  ('Guitarra Iniciación',  'guitarra-iniciacion',  'Curso de guitarra para principiantes. Aprende acordes, ritmos y tus primeras canciones.'),
  ('Guitarra Avanzado',    'guitarra-avanzado',    'Técnicas avanzadas de guitarra: fingerpicking, escalas modales y armonía aplicada.'),
  ('Bandurria Iniciación', 'bandurria-iniciacion', 'Iniciación a la bandurria: pulsación, escalas y repertorio tradicional.'),
  ('Bandurria Avanzado',   'bandurria-avanzado',   'Técnica avanzada de bandurria: ligados, trémolo y acompañamiento.'),
  ('Conjunto',             'conjunto',             'Música en conjunto: ensamble, repertorio y dinámica de grupo.')
ON CONFLICT DO NOTHING;

-- Enrollments table
CREATE TABLE IF NOT EXISTS public.enrollments (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id   UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  course_id BIGINT NOT NULL REFERENCES public.courses(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, course_id)
);

ALTER TABLE public.enrollments ENABLE ROW LEVEL SECURITY;

-- Students can read their own enrollments
DROP POLICY IF EXISTS "enrollments_read_own" ON public.enrollments;
CREATE POLICY "enrollments_read_own" ON public.enrollments
  FOR SELECT USING (auth.uid() = user_id);

-- Students can enroll themselves
DROP POLICY IF EXISTS "enrollments_insert_own" ON public.enrollments;
CREATE POLICY "enrollments_insert_own" ON public.enrollments
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Students can unenroll themselves
DROP POLICY IF EXISTS "enrollments_delete_own" ON public.enrollments;
CREATE POLICY "enrollments_delete_own" ON public.enrollments
  FOR DELETE USING (auth.uid() = user_id);

-- Admin-only write policies for courses
DROP POLICY IF EXISTS "courses_insert_admin" ON public.courses;
CREATE POLICY "courses_insert_admin" ON public.courses
  FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
  );

DROP POLICY IF EXISTS "courses_update_admin" ON public.courses;
CREATE POLICY "courses_update_admin" ON public.courses
  FOR UPDATE USING (
    EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
  );

DROP POLICY IF EXISTS "courses_delete_admin" ON public.courses;
CREATE POLICY "courses_delete_admin" ON public.courses
  FOR DELETE USING (
    EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
  );

-- Modules table
CREATE TABLE IF NOT EXISTS public.modules (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id   BIGINT NOT NULL REFERENCES public.courses(id) ON DELETE CASCADE,
  name        TEXT NOT NULL,
  description TEXT,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.modules ENABLE ROW LEVEL SECURITY;

-- Anyone can read modules
DROP POLICY IF EXISTS "modules_read_public" ON public.modules;
CREATE POLICY "modules_read_public" ON public.modules
  FOR SELECT USING (true);

-- Admin write
DROP POLICY IF EXISTS "modules_insert_admin" ON public.modules;
CREATE POLICY "modules_insert_admin" ON public.modules
  FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
  );

DROP POLICY IF EXISTS "modules_update_admin" ON public.modules;
CREATE POLICY "modules_update_admin" ON public.modules
  FOR UPDATE USING (
    EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
  );

DROP POLICY IF EXISTS "modules_delete_admin" ON public.modules;
CREATE POLICY "modules_delete_admin" ON public.modules
  FOR DELETE USING (
    EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
  );

-- Lessons table
CREATE TABLE IF NOT EXISTS public.lessons (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module_id   BIGINT NOT NULL REFERENCES public.modules(id) ON DELETE CASCADE,
  name        TEXT NOT NULL,
  description TEXT,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  audio_url   TEXT,
  pdf_url     TEXT,
  video_url   TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.lessons ENABLE ROW LEVEL SECURITY;

-- Anyone can read lessons
DROP POLICY IF EXISTS "lessons_read_public" ON public.lessons;
CREATE POLICY "lessons_read_public" ON public.lessons
  FOR SELECT USING (true);

-- Admin write
DROP POLICY IF EXISTS "lessons_insert_admin" ON public.lessons;
CREATE POLICY "lessons_insert_admin" ON public.lessons
  FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
  );

DROP POLICY IF EXISTS "lessons_update_admin" ON public.lessons;
CREATE POLICY "lessons_update_admin" ON public.lessons
  FOR UPDATE USING (
    EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
  );

DROP POLICY IF EXISTS "lessons_delete_admin" ON public.lessons;
CREATE POLICY "lessons_delete_admin" ON public.lessons
  FOR DELETE USING (
    EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
  );

-- Storage buckets (idempotent)
INSERT INTO storage.buckets (id, name, public) VALUES ('audio', 'audio', true) ON CONFLICT DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('pdfs', 'pdfs', true) ON CONFLICT DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('videos', 'videos', true) ON CONFLICT DO NOTHING;

-- Storage RLS
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;

-- Anyone can read from storage (public buckets)
DROP POLICY IF EXISTS "storage_read_public" ON storage.objects;
CREATE POLICY "storage_read_public" ON storage.objects
  FOR SELECT USING (bucket_id IN ('audio', 'pdfs', 'videos'));

-- Only admin can upload files
DROP POLICY IF EXISTS "storage_insert_admin" ON storage.objects;
CREATE POLICY "storage_insert_admin" ON storage.objects
  FOR INSERT WITH CHECK (
    bucket_id IN ('audio', 'pdfs', 'videos')
    AND EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
  );

-- Only admin can update files
DROP POLICY IF EXISTS "storage_update_admin" ON storage.objects;
CREATE POLICY "storage_update_admin" ON storage.objects
  FOR UPDATE USING (
    bucket_id IN ('audio', 'pdfs', 'videos')
    AND EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
  );

-- Only admin can delete files
DROP POLICY IF EXISTS "storage_delete_admin" ON storage.objects;
CREATE POLICY "storage_delete_admin" ON storage.objects
  FOR DELETE USING (
    bucket_id IN ('audio', 'pdfs', 'videos')
    AND EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
  );

-- Future tables: progress
