-- Users table (synced from auth.users via trigger)
CREATE TABLE public.users (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  name TEXT NOT NULL DEFAULT '',
  last_name TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL DEFAULT 'student' CHECK (role IN ('student', 'admin')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Auto-create user row on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (id, email, name, last_name)
  VALUES (
    NEW.id,
    NEW.email,
    NEW.raw_user_meta_data->>'name',
    NEW.raw_user_meta_data->>'lastName'
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Row Level Security
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Users can read their own row
CREATE POLICY "users_read_own" ON public.users
  FOR SELECT USING (auth.uid() = id);

-- Courses table
CREATE TABLE public.courses (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name      TEXT NOT NULL,
  slug      TEXT NOT NULL UNIQUE,
  description TEXT,
  image_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;

-- Anyone can read courses (public catalog)
CREATE POLICY "courses_read_public" ON public.courses
  FOR SELECT USING (true);

-- Seed data
INSERT INTO public.courses (name, slug, description) VALUES
  ('Guitarra Iniciación',  'guitarra-iniciacion',  'Curso de guitarra para principiantes. Aprende acordes, ritmos y tus primeras canciones.'),
  ('Guitarra Avanzado',    'guitarra-avanzado',    'Técnicas avanzadas de guitarra: fingerpicking, escalas modales y armonía aplicada.'),
  ('Bandurria Iniciación', 'bandurria-iniciacion', 'Iniciación a la bandurria: pulsación, escalas y repertorio tradicional.'),
  ('Bandurria Avanzado',   'bandurria-avanzado',   'Técnica avanzada de bandurria: ligados, trémolo y acompañamiento.'),
  ('Conjunto',             'conjunto',             'Música en conjunto: ensamble, repertorio y dinámica de grupo.');

-- Future tables: modules, lessons, enrollments, progress
